### ISSUE TITLE
review

### ISSUE THREAD

**Issue by amunozdev** [dylanpilsner/ecommerce-backend#1]
Buenas Dylan, estaba mirando tu desafío y al momento de probar el endpoint `/api/auth` para que se me envíe el código al mail, nunca me llega, probé con tres mails diferentes
No sé si me pasa a mí solamente o algo no está funcionando correctamente, cualquier cosita chifla por el server de discord!
Cuando lo arregles mencióname así lo volvemos a mirar

**Comment by dylanpilsner** [comment]
Buenas @alexismunoz1 ! Cómo va? Consulta, probaste revisando la casilla de spam? Tengo entendido que el correo a veces puede redireccionarlo ahí. En mi caso, en algunos mails me los trae en la bandeja de entrada, y otros en spam. Acabo de probar nuevamente y me llegó el mail:

![image](https://user-images.githubusercontent.com/87613658/219899150-ea57e0d1-d60e-42ed-8772-cb955b57f59a.png)

Quedo atento, muchas gracias!

**Comment by amunozdev** [comment]
Ahora si @dylanpilsner !!
Por alguna razón no me llegaban ni a spam, seguramente le estaba pifiando en algo

Che la verdad que felicito por el desafío, se nota el laburo que le metiste, se ve reflejado en lo bien ordenado que está el proyecto y cosas como la manera en nombrar funciones, variables, etc. Esos detalles hacen la diferencia. 
Realmente me cuesta encontrar cosas para mejorar en el proyecto, esta podría ser una:

### models
- Todas las clases tienen un método pull() y un método push() que hacen los mismos en todos los models
- Estaría genial hacer una clase que tenga estos dos métodos y extenderla para usarla en los models, reutilizar y no repetir lógica
- La tiro como idea, como lo hiciste funciona y esta joya

A seguir así y éxitos en lo que sigue!!

**Comment by dylanpilsner** [comment]
Genial @alexismunoz1! Muchísimas gracias por el feedback, y es cierto lo que me comentás sobre la función pull y push. Lo voy a tener en cuenta para corregirlo. De nuevo, gracias!
